server:
  port: 8000

spring:
  application:
    name: xyf-crowd-pay


  redis:
    host: 120.26.64.250
    password: xyf123456
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    app-id: 2021000118645470
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm9d3goL2/aPJB34LzNrpMHrg8HCVkMugx+pyyCHvRmsgqZE7OZ1CTmUB5PXtdk+cqUHVyJSzRoBTtlnS5lWG2W4tc3HmWg0H2Jma5Wb2mMBjRbmoT6chZY6dSX1p6FOYT4BM7Jc6WqIX7tWzFNLTVGis+gSxsNY62p9E+/Linx7JZlpignNikR1qNvpQS6xXewOujvIB5jjtmjHG/dgpnhh+gziwdYdIF5j6NiqB6MaITvlOZtMFx1/f/L+qveJoNTTvkakwUzV6KJhXcGfNwF0ofBRoQFR+FhiV65GfoxmTEmKZSpYB+WKttfQVf5Sdb4RoSb1lTFh/AKgkwn2ftAgMBAAECggEAB422FRSQoRlJZIuNLB28vfbh1O5dDrRy5tf0wOU7XNdI2QoiupnX/mV/kjyi2S/41GRBfAGMjotUhw84hrDoc8yeeHwNEC8uC8ne+eHCf8NLTCZXrED2bHzitApWWJGbeyi3FgT23MARF7s0iZOB3uZJMJG9hcPCiib7g4MBg62lVIILqtjpGV40C8jcHiUQGcoayFX7AGVB+qgTAaIk9fcrLVH6iifbvktt81qRfZT5TYCjGnZ1bFvEb+DzpAAr8/QogjGAU8Yx6j1TDs6eMFaUo9t1DYeZ/ZRwtko6mwvr1eG92Oz2+dr04mw8cbtamFDDvuYvjMugmTMrKzJobQKBgQDtSQ41JooiOIQ3OzOyhG5exS6FkMBkTUEtkNw/h8AIu1xe+R5XRgAaNjnEaxR8bBf0VHlDZy9d2w7V/P4WYfgbaRRq49Qfzt62S9EKKHO3qupxzGtKeJqGYoRV/WL9EcfcROa3KZ02q51XeAhXSlGcEHly2BnnqA9EsdMPB4MBdwKBgQC0IOexiby40H7ko+IuDdLyxiYqHaAKsySHJpW3/AlcO/7UNk7iCjO1CP0vNauve3QsdD61RaPgiinaHgySV7TSNVnYT5ZjE2C9ch2s+YbkZbPMHF7ZFx7F7o+kmiz8NrNXNx58377SK6seTvsJm65IEFEc8G6d4Eic/fSEXELauwKBgEdjVE/vUV2sTTLkr9AEgcQnZLCwdQF4MKTJ0UmXyNGXtNmp71Pobn10VPrgEGDCkI5kn7sEnz6IejUtETCgtulgOtFRy+7p6R1FQBXjR7U5SaGFE75q/Gpz10abnh1vLQb6/8KZVYAuL38yUKgaZuUiG7fOhjSo3jcXnN0HsIVPAoGBALKxnghjYwRZWjkKV5xmfGn5puzK/PUAaPFmlsqxzrtgjVoLElBt3IPxCfLmpI5uw35CR99e2ccsaX6HpuMa/Tg4UwwjUEazd5oY9lWeKXK1bhvD3Vgx9oZXNssNZClFPr774FPzR4OKbLShl6sddVTqUv2Ji8M1N/P+f687M9t3AoGASNCe3j4HgGZQkERgJ11kY/vId7YgISLvLmdu+3S84hUIHINYERVQML+jWyiwBmWSHFP4Y1OAHmqObuBT6vEagKdRLiXUXklMeaTdErIYpGo8ffLiJ9LMik+jZxwRmTBNfr4D85VVrs177QXACydoRQYX5XGFQRLJwXER44X280A=
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoGkCjyq6jdwAp/0pbhGNcHi49jE+POLGkxjbKPN6k2gRqxGOw4pt6x9SxSdaN73b3RSmFMIRKB4euAF+Tivde16qwpHALeVdvXWiycljvHOa7VBMYI0hAY1SUgVXiescaldRT84LZLX7NI8OpqQqBQQzGgPbqXf2LW4xzq7C+EexUDZE7wXDBb7CYeShFC0WLYQJ2pkyX3j9OlrAjERx3eitqmecz+QefXi/HFgVBTiTw46HxYPVET8HCgA8o2cPrkheikJw49MLynk1+25fJo3oMz1BydCbSd4o+kppkCs8pGDLJlgQoCeizRw4ADN/VLupk6p6foEmYV5+ACBtHQIDAQAB
    notify-url: http://www.xyf2021.ltd/pay/notify
    return-url: http://www.crowd.com/pay/return
    sign-type: RSA2
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do

